name: funes
version: 0.1.0.0
github: "Arthi-chaud/funes"
license: BSD-3-Clause
author: "Arthur Jamet"
copyright: "2025 Arthur Jamet"

extra-source-files:
  - README.md

description: A NES Emulator written in Haskell

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - mtl
  - containers

default-extensions:
  - BinaryLiterals
  - LambdaCase
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - TupleSections
  - TypeFamilies

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  fake-snake:
    main: Snake.hs
    source-dirs: examples
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - funes
      - sdl2
      - array
      - random

tests:
  unit:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - funes
      - hspec
  nestest:
    main: Spec.hs
    source-dirs: test/nestest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - funes
      - hspec
