name: funes
version: 0.1.0.0
github: "Arthi-chaud/funes"
license: BSD-3-Clause
author: "Arthur Jamet"
copyright: "2025 Arthur Jamet"

extra-source-files:
  - README.md

description: A NES Emulator written in Haskell

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - mtl

default-extensions:
  - BinaryLiterals
  - LambdaCase
  - GeneralizedNewtypeDeriving

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  funes:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - funes

tests:
  funes-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - funes
      - hspec
