module Nes.CPU.Instructions.Map (opcodeMap, OpType (..), OpCodeEntry) where

import Data.ByteString
import Data.Map (Map, fromList)
import Nes.CPU.Instructions.Access
import Nes.CPU.Instructions.Addressing
import Nes.CPU.Instructions.Arith
import Nes.CPU.Instructions.Bitwise
import Nes.CPU.Instructions.Branch
import Nes.CPU.Instructions.Compare
import Nes.CPU.Instructions.Flags
import Nes.CPU.Instructions.Interrupt (brk)
import Nes.CPU.Instructions.Jump
import Nes.CPU.Instructions.Noop
import Nes.CPU.Instructions.Stack
import Nes.CPU.Instructions.Transfer
import Nes.CPU.Instructions.Unofficial
import Nes.CPU.Monad
import Nes.Memory (Byte)
import Prelude hiding (and)

data OpType = Official | Unofficial deriving (Eq)

type OpCodeEntry r = (ByteString, AddressingMode -> CPU r (), AddressingMode, OpType)

-- | Maps op code to the function that executes it and the addressing mode
opcodeMap :: Map Byte (OpCodeEntry r)
opcodeMap =
    fromList
        [ (0x85, ("STA", sta, ZeroPage, Official))
        , (0x95, ("STA", sta, ZeroPageX, Official))
        , (0x8D, ("STA", sta, Absolute, Official))
        , (0x9D, ("STA", sta, AbsoluteX, Official))
        , (0x99, ("STA", sta, AbsoluteY, Official))
        , (0x81, ("STA", sta, IndirectX, Official))
        , (0x91, ("STA", sta, IndirectY, Official))
        , (0x86, ("STX", stx, ZeroPage, Official))
        , (0x96, ("STX", stx, ZeroPageY, Official))
        , (0x8E, ("STX", stx, Absolute, Official))
        , (0x84, ("STY", sty, ZeroPage, Official))
        , (0x94, ("STY", sty, ZeroPageX, Official))
        , (0x8c, ("STY", sty, Absolute, Official))
        , (0xa9, ("LDA", lda, Immediate, Official))
        , (0xa5, ("LDA", lda, ZeroPage, Official))
        , (0xb5, ("LDA", lda, ZeroPageX, Official))
        , (0xad, ("LDA", lda, Absolute, Official))
        , (0xbd, ("LDA", lda, AbsoluteX, Official))
        , (0xb9, ("LDA", lda, AbsoluteY, Official))
        , (0xa1, ("LDA", lda, IndirectX, Official))
        , (0xb1, ("LDA", lda, IndirectY, Official))
        , (0xa2, ("LDX", ldx, Immediate, Official))
        , (0xa6, ("LDX", ldx, ZeroPage, Official))
        , (0xb6, ("LDX", ldx, ZeroPageY, Official))
        , (0xae, ("LDX", ldx, Absolute, Official))
        , (0xbe, ("LDX", ldx, AbsoluteY, Official))
        , (0xa0, ("LDY", ldy, Immediate, Official))
        , (0xa4, ("LDY", ldy, ZeroPage, Official))
        , (0xb4, ("LDY", ldy, ZeroPageX, Official))
        , (0xac, ("LDY", ldy, Absolute, Official))
        , (0xbc, ("LDY", ldy, AbsoluteX, Official))
        , (0xe6, ("INC", inc, ZeroPage, Official))
        , (0xf6, ("INC", inc, ZeroPageX, Official))
        , (0xee, ("INC", inc, Absolute, Official))
        , (0xfe, ("INC", inc, AbsoluteX, Official))
        , (0xc6, ("DEC", dec, ZeroPage, Official))
        , (0xd6, ("DEC", dec, ZeroPageX, Official))
        , (0xce, ("DEC", dec, Absolute, Official))
        , (0xde, ("DEC", dec, AbsoluteX, Official))
        , (0x50, ("BVC", bvc, Relative, Official))
        , (0x70, ("BVS", bvs, Relative, Official))
        , (0x90, ("BCC", bcc, Relative, Official))
        , (0xb0, ("BCS", bcs, Relative, Official))
        , (0xf0, ("BEQ", beq, Relative, Official))
        , (0xd0, ("BNE", bne, Relative, Official))
        , (0x30, ("BMI", bmi, Relative, Official))
        , (0x10, ("BPL", bpl, Relative, Official))
        , (0xc9, ("CMP", cmp, Immediate, Official))
        , (0xc5, ("CMP", cmp, ZeroPage, Official))
        , (0xd5, ("CMP", cmp, ZeroPageX, Official))
        , (0xcd, ("CMP", cmp, Absolute, Official))
        , (0xdd, ("CMP", cmp, AbsoluteX, Official))
        , (0xd9, ("CMP", cmp, AbsoluteY, Official))
        , (0xc1, ("CMP", cmp, IndirectX, Official))
        , (0xd1, ("CMP", cmp, IndirectY, Official))
        , (0xe0, ("CPX", cpx, Immediate, Official))
        , (0xe4, ("CPX", cpx, ZeroPage, Official))
        , (0xec, ("CPX", cpx, Absolute, Official))
        , (0xc0, ("CPY", cpy, Immediate, Official))
        , (0xc4, ("CPY", cpy, ZeroPage, Official))
        , (0xcc, ("CPY", cpy, Absolute, Official))
        , (0x4c, ("JMP", jmp, Absolute, Official))
        , (0x6c, ("JMP", jmp, Indirect, Official))
        , (0x20, ("JSR", const jsr, Absolute, Official))
        , (0x29, ("AND", and, Immediate, Official))
        , (0x25, ("AND", and, ZeroPage, Official))
        , (0x35, ("AND", and, ZeroPageX, Official))
        , (0x2d, ("AND", and, Absolute, Official))
        , (0x3d, ("AND", and, AbsoluteX, Official))
        , (0x39, ("AND", and, AbsoluteY, Official))
        , (0x21, ("AND", and, IndirectX, Official))
        , (0x31, ("AND", and, IndirectY, Official))
        , (0x09, ("ORA", ora, Immediate, Official))
        , (0x05, ("ORA", ora, ZeroPage, Official))
        , (0x15, ("ORA", ora, ZeroPageX, Official))
        , (0x0d, ("ORA", ora, Absolute, Official))
        , (0x1d, ("ORA", ora, AbsoluteX, Official))
        , (0x19, ("ORA", ora, AbsoluteY, Official))
        , (0x01, ("ORA", ora, IndirectX, Official))
        , (0x11, ("ORA", ora, IndirectY, Official))
        , (0x49, ("EOR", eor, Immediate, Official))
        , (0x45, ("EOR", eor, ZeroPage, Official))
        , (0x55, ("EOR", eor, ZeroPageX, Official))
        , (0x4d, ("EOR", eor, Absolute, Official))
        , (0x5d, ("EOR", eor, AbsoluteX, Official))
        , (0x59, ("EOR", eor, AbsoluteY, Official))
        , (0x41, ("EOR", eor, IndirectX, Official))
        , (0x51, ("EOR", eor, IndirectY, Official))
        , (0x2a, ("ROL", rol, Accumulator, Official))
        , (0x26, ("ROL", rol, ZeroPage, Official))
        , (0x36, ("ROL", rol, ZeroPageX, Official))
        , (0x2e, ("ROL", rol, Absolute, Official))
        , (0x3e, ("ROL", rol, AbsoluteX, Official))
        , (0x6a, ("ROR", ror, Accumulator, Official))
        , (0x66, ("ROR", ror, ZeroPage, Official))
        , (0x76, ("ROR", ror, ZeroPageX, Official))
        , (0x6e, ("ROR", ror, Absolute, Official))
        , (0x7e, ("ROR", ror, AbsoluteX, Official))
        , (0x24, ("BIT", bit, ZeroPage, Official))
        , (0x2c, ("BIT", bit, Absolute, Official))
        , (0xe9, ("SBC", sbc, Immediate, Official))
        , (0xe5, ("SBC", sbc, ZeroPage, Official))
        , (0xf5, ("SBC", sbc, ZeroPageX, Official))
        , (0xed, ("SBC", sbc, Absolute, Official))
        , (0xfd, ("SBC", sbc, AbsoluteX, Official))
        , (0xf9, ("SBC", sbc, AbsoluteY, Official))
        , (0xe1, ("SBC", sbc, IndirectX, Official))
        , (0xf1, ("SBC", sbc, IndirectY, Official))
        , (0xeb, ("SBC", sbc, Immediate, Unofficial))
        , (0x69, ("ADC", adc, Immediate, Official))
        , (0x65, ("ADC", adc, ZeroPage, Official))
        , (0x75, ("ADC", adc, ZeroPageX, Official))
        , (0x6d, ("ADC", adc, Absolute, Official))
        , (0x7d, ("ADC", adc, AbsoluteX, Official))
        , (0x79, ("ADC", adc, AbsoluteY, Official))
        , (0x61, ("ADC", adc, IndirectX, Official))
        , (0x71, ("ADC", adc, IndirectY, Official))
        , (0x0A, ("ASL", asl, Accumulator, Official))
        , (0x06, ("ASL", asl, ZeroPage, Official))
        , (0x16, ("ASL", asl, ZeroPageX, Official))
        , (0x0e, ("ASL", asl, Absolute, Official))
        , (0x1e, ("ASL", asl, AbsoluteX, Official))
        , (0x4A, ("LSR", lsr, Accumulator, Official))
        , (0x46, ("LSR", lsr, ZeroPage, Official))
        , (0x56, ("LSR", lsr, ZeroPageX, Official))
        , (0x4e, ("LSR", lsr, Absolute, Official))
        , (0x5e, ("LSR", lsr, AbsoluteX, Official))
        , -- W/o addressing
          (0x18, ("CLC", const clc, None, Official))
        , (0xd8, ("CLD", const cld, None, Official))
        , (0x58, ("CLI", const cli, None, Official))
        , (0xB8, ("CLV", const clv, None, Official))
        , (0x38, ("SEC", const sec, None, Official))
        , (0xf8, ("SED", const sed, None, Official))
        , (0x78, ("SEI", const sei, None, Official))
        , (0xca, ("DEX", const dex, None, Official))
        , (0x88, ("DEY", const dey, None, Official))
        , (0xaa, ("TAX", const tax, None, Official))
        , (0xa8, ("TAY", const tay, None, Official))
        , (0x8a, ("TXA", const txa, None, Official))
        , (0x98, ("TYA", const tya, None, Official))
        , (0x9a, ("TXS", const txs, None, Official))
        , (0xba, ("TSX", const tsx, None, Official))
        , (0xe8, ("INX", const inx, None, Official))
        , (0xc8, ("INY", const iny, None, Official))
        , (0x60, ("RTS", const rts, None, Official))
        , (0x40, ("RTI", const rti, None, Official))
        , (0x48, ("PHA", const pha, None, Official))
        , (0x08, ("PHP", const php, None, Official))
        , (0x68, ("PLA", const pla, None, Official))
        , (0x28, ("PLP", const plp, None, Official))
        , (0xea, ("NOP", noop, None, Official))
        , (0x04, ("NOP", noop, ZeroPage, Unofficial))
        , (0x44, ("NOP", noop, ZeroPage, Unofficial))
        , (0x64, ("NOP", noop, ZeroPage, Unofficial))
        , (0x80, ("NOP", noop, Immediate, Unofficial))
        , (0x82, ("NOP", noop, Immediate, Unofficial))
        , (0xc2, ("NOP", noop, Immediate, Unofficial))
        , (0xe2, ("NOP", noop, Immediate, Unofficial))
        , (0x89, ("NOP", noop, Immediate, Unofficial))
        , (0x0c, ("NOP", noop, Absolute, Unofficial))
        , (0x14, ("NOP", noop, ZeroPageX, Unofficial))
        , (0x34, ("NOP", noop, ZeroPageX, Unofficial))
        , (0x54, ("NOP", noop, ZeroPageX, Unofficial))
        , (0x74, ("NOP", noop, ZeroPageX, Unofficial))
        , (0xd4, ("NOP", noop, ZeroPageX, Unofficial))
        , (0xf4, ("NOP", noop, ZeroPageX, Unofficial))
        , (0x1a, ("NOP", noop, None, Unofficial))
        , (0x3a, ("NOP", noop, None, Unofficial))
        , (0x5a, ("NOP", noop, None, Unofficial))
        , (0x7a, ("NOP", noop, None, Unofficial))
        , (0xda, ("NOP", noop, None, Unofficial))
        , (0xfa, ("NOP", noop, None, Unofficial))
        , (0x1c, ("NOP", noop, AbsoluteX, Unofficial))
        , (0x3c, ("NOP", noop, AbsoluteX, Unofficial))
        , (0x5c, ("NOP", noop, AbsoluteX, Unofficial))
        , (0x7c, ("NOP", noop, AbsoluteX, Unofficial))
        , (0xdc, ("NOP", noop, AbsoluteX, Unofficial))
        , (0xfc, ("NOP", noop, AbsoluteX, Unofficial))
        , (0xa3, ("LAX", lax, IndirectX, Unofficial))
        , (0xa7, ("LAX", lax, ZeroPage, Unofficial))
        , (0xaf, ("LAX", lax, Absolute, Unofficial))
        , (0xb3, ("LAX", lax, IndirectY, Unofficial))
        , (0xb7, ("LAX", lax, ZeroPageY, Unofficial))
        , (0xbf, ("LAX", lax, AbsoluteY, Unofficial))
        , (0x83, ("SAX", sax, IndirectX, Unofficial))
        , (0x87, ("SAX", sax, ZeroPage, Unofficial))
        , (0x8f, ("SAX", sax, Absolute, Unofficial))
        , (0x97, ("SAX", sax, ZeroPageY, Unofficial))
        , (0xc3, ("DCP", dcp, IndirectX, Unofficial))
        , (0xc7, ("DCP", dcp, ZeroPage, Unofficial))
        , (0xcf, ("DCP", dcp, Absolute, Unofficial))
        , (0xd3, ("DCP", dcp, IndirectY, Unofficial))
        , (0xd7, ("DCP", dcp, ZeroPageX, Unofficial))
        , (0xdb, ("DCP", dcp, AbsoluteY, Unofficial))
        , (0xdf, ("DCP", dcp, AbsoluteX, Unofficial))
        , (0xe3, ("ISB", isb, IndirectX, Unofficial))
        , (0xe7, ("ISB", isb, ZeroPage, Unofficial))
        , (0xef, ("ISB", isb, Absolute, Unofficial))
        , (0xf3, ("ISB", isb, IndirectY, Unofficial))
        , (0xf7, ("ISB", isb, ZeroPageX, Unofficial))
        , (0xf7, ("ISB", isb, ZeroPageX, Unofficial))
        , (0xfb, ("ISB", isb, AbsoluteY, Unofficial))
        , (0xff, ("ISB", isb, AbsoluteX, Unofficial))
        , (0x03, ("SLO", slo, IndirectX, Unofficial))
        , (0x07, ("SLO", slo, ZeroPage, Unofficial))
        , (0x0f, ("SLO", slo, Absolute, Unofficial))
        , (0x13, ("SLO", slo, IndirectY, Unofficial))
        , (0x17, ("SLO", slo, ZeroPageX, Unofficial))
        , (0x1b, ("SLO", slo, AbsoluteY, Unofficial))
        , (0x1f, ("SLO", slo, AbsoluteX, Unofficial))
        , (0x23, ("RLA", rla, IndirectX, Unofficial))
        , (0x27, ("RLA", rla, ZeroPage, Unofficial))
        , (0x2f, ("RLA", rla, Absolute, Unofficial))
        , (0x33, ("RLA", rla, IndirectY, Unofficial))
        , (0x37, ("RLA", rla, ZeroPageX, Unofficial))
        , (0x3b, ("RLA", rla, AbsoluteY, Unofficial))
        , (0x3f, ("RLA", rla, AbsoluteX, Unofficial))
        , (0x0b, ("ANC", anc, Immediate, Unofficial))
        , (0x2b, ("ANC", anc, Immediate, Unofficial))
        , (0x43, ("SRE", sre, IndirectX, Unofficial))
        , (0x47, ("SRE", sre, ZeroPage, Unofficial))
        , (0x4f, ("SRE", sre, Absolute, Unofficial))
        , (0x53, ("SRE", sre, IndirectY, Unofficial))
        , (0x57, ("SRE", sre, ZeroPageX, Unofficial))
        , (0x5b, ("SRE", sre, AbsoluteY, Unofficial))
        , (0x5f, ("SRE", sre, AbsoluteX, Unofficial))
        , (0x63, ("RRA", rra, IndirectX, Unofficial))
        , (0x67, ("RRA", rra, ZeroPage, Unofficial))
        , (0x6f, ("RRA", rra, Absolute, Unofficial))
        , (0x73, ("RRA", rra, IndirectY, Unofficial))
        , (0x77, ("RRA", rra, ZeroPageX, Unofficial))
        , (0x7b, ("RRA", rra, AbsoluteY, Unofficial))
        , (0x7f, ("RRA", rra, AbsoluteX, Unofficial))
        , (0x00, ("BRK", const brk, None, Official))
        , (0x02, ("KIL", const kil, None, Unofficial))
        , (0x12, ("KIL", const kil, None, Unofficial))
        , (0x22, ("KIL", const kil, None, Unofficial))
        , (0x32, ("KIL", const kil, None, Unofficial))
        , (0x42, ("KIL", const kil, None, Unofficial))
        , (0x52, ("KIL", const kil, None, Unofficial))
        , (0x62, ("KIL", const kil, None, Unofficial))
        , (0x72, ("KIL", const kil, None, Unofficial))
        , (0x92, ("KIL", const kil, None, Unofficial))
        , (0xB2, ("KIL", const kil, None, Unofficial))
        , (0xD2, ("KIL", const kil, None, Unofficial))
        , (0xF2, ("KIL", const kil, None, Unofficial))
        ]
